spring.application.name=AuthService

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${AUTH_SERVICE_DATABASE_URL}
spring.datasource.username=${AUTH_SERVICE_DATABASE_USERNAME}
spring.datasource.password=${AUTH_SERVICE_DATABASE_PASSWORD}

server.port=${SERVER_PORT}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
logging.level.org.springframework.security=trace

# OAuth2 Client Configuration

